export const CARDS = "CARDS";
export const CARDS_SUCCESS = "CARDS_SUCCESS";
export const CARDS_FAILURE = "CARDS_FAILURE";

export const FETCH_CARDS="FETCH_CARDS";
export const FETCH_CARDS_SUCCESS="FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILURE="FETCH_CARDS_FAILURE";

export const FETCH_USER_CARDS="FETCH_USER_CARDS";
export const FETCH_USER_CARDS_SUCCESS="FETCH_USER_CARDS_SUCCESS";
export const FETCH_USER_CARDS_FAILURE="FETCH_USER_CARDS_FAILURE";

export const FETCH_SINGLE_CARD="FETCH_SINGLE_CARD";
export const FETCH_SINGLE_CARD_SUCCESS="FETCH_SINGLE_CARD_SUCCESS";
export const FETCH_SINGLE_CARD_FAILURE="FETCH_SINGLE_CARD_FAILURE";

export const SEARCH_BY_NAME = "SEARCH_BY_NAME";
export const SEARCH_BY_NAME_SUCCESS = "SEARCH_BY_NAME_SUCCESS";
export const SEARCH_BY_NAME_FAILURE = "SEARCH_BY_NAME_FAILURE";

export const SEARCH_BY_TAG = "SEARCH_BY_TAG";
export const SEARCH_BY_TAG_SUCCESS = "SEARCH_BY_TAG_SUCCESS";
export const SEARCH_BY_TAG_FAILURE = "SEARCH_BY_TAG_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";
