export const CARDS = "CARDS";
export const CARDS_SUCCESS = "CARDS_SUCCESS";
export const CARDS_FAILURE = "CARDS_FAILURE";

export const FETCH_CARDS="FETCH_CARDS";
export const FETCH_CARDS_SUCCESS="FETCH_CARDS_SUCCESS";
export const FETCH_CARDS_FAILURE="FETCH_CARDS_FAILURE";
